#!/data/data/com.termux/files/usr/bin/bash

cd ~/storage/Revancify > /dev/null 2>&1 || echo "Revancify not installed"

while getopts 'f' flag; do
  case "${flag}" in
    f) git checkout . && git pull & ;;
    *) echo "Not a valid option"
  esac
done
    
bash revancify.sh
